import {themes as prismThemes} from 'prism-react-renderer';
import type {Config} from '@docusaurus/types';
import type * as Preset from '@docusaurus/preset-classic';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

const config: Config = {
    title: 'Stellaris Wiki',
    tagline: 'Unofficial Stellaris knowledge base',
    favicon: 'img/favicon.ico',

    // Future flags, see https://docusaurus.io/docs/api/docusaurus-config#future
    future: {
        v4: true, // Improve compatibility with the upcoming Docusaurus v4
    },

    // Set the production url of your site here
    url: 'https://danaketh.github.io',
    // Set the /<baseUrl>/ pathname under which your site is served
    // For GitHub pages deployment, it is often '/<projectName>/'
    baseUrl: '/StellarisWiki/',

    // GitHub pages deployment config.
    // If you aren't using GitHub pages, you don't need these.
    organizationName: 'danaketh', // Usually your GitHub org/user name.
    projectName: 'StellarisWiki', // Usually your repo name.

    onBrokenLinks: 'throw',

    // Even if you don't use internationalization, you can use this field to set
    // useful metadata like html lang. For example, if your site is Chinese, you
    // may want to replace "en" with "zh-Hans".
    i18n: {
        defaultLocale: 'en',
        locales: ['en'],
    },

    presets: [
        [
            'classic',
            {
                docs: {
                    sidebarPath: './sidebars.ts',
                    routeBasePath: '/',
                    sidebarItemsGenerator: async function ({
                        defaultSidebarItemsGenerator,
                        ...args
                    }) {
                        const sidebarItems = await defaultSidebarItemsGenerator(args);

                        // Filter out index.md from autogenerated items in subdirectories
                        const filteredItems = sidebarItems.filter((item) => {
                            if (item.type === 'doc' && item.id) {
                                // Keep top-level docs but exclude index files from research subdirectories
                                return !item.id.match(/research\/(engineering|physics|society)\/index$/);
                            }
                            return true;
                        });

                        // Sort items by their label (alphabetically)
                        filteredItems.sort((a, b) => {
                            const labelA = (a.label || '').toLowerCase();
                            const labelB = (b.label || '').toLowerCase();
                            return labelA.localeCompare(labelB);
                        });

                        return filteredItems;
                    },
                },
                blog: {
                    showReadingTime: true,
                    feedOptions: {
                        type: ['rss', 'atom'],
                        xslt: true,
                    },
                    // Please change this to your repo.
                    // Remove this to remove the "edit this page" links.
                    editUrl:
                        'https://github.com/facebook/docusaurus/tree/main/packages/create-docusaurus/templates/shared/',
                    // Useful options to enforce blogging best practices
                    onInlineTags: 'warn',
                    onInlineAuthors: 'warn',
                    onUntruncatedBlogPosts: 'warn',
                },
                theme: {
                    customCss: './src/css/custom.css',
                },
            } satisfies Preset.Options,
        ],
    ],

    plugins: [
        [
            './plugins/docusaurus-plugin-remote-content/src/index.js',
            {
                sources: [
                    {
                        name: 'research-engineering',
                        sourceUrl: 'https://cdn.statically.io/gh/danaketh/StellarisDataParser/main/output/research-engineering.json',
                        outDir: 'research/engineering',
                        template: 'templates/research.md',
                        dataKey: 'technologies',
                        getPageRoute: (item) => item.key || item.id || item.slug,
                        getPageTitle: (item) => item.name || item.title,
                        getPageDescription: (item) => item.description || '',
                        frontmatter: (item) => ({
                            sidebar_label: item.name || item.title,
                            tags: item.tags || [],
                        }),
                    },
                ],
            },
        ],
    ],

    themeConfig: {
        // Replace with your project's social card
        image: 'img/docusaurus-social-card.jpg',
        colorMode: {
            respectPrefersColorScheme: true,
        },
        navbar: {
            title: 'Stellaris Wiki',
            logo: {
                alt: 'My Site Logo',
                src: 'img/logo.svg',
            },
            items: [
                {
                    to: '/',
                    position: 'left',
                    label: 'Home',
                },
                {
                    to: '/research',
                    label: 'Research',
                    position: 'left'
                },
            ],
        },
        footer: {
            style: 'dark',
            links: [
                {
                    title: 'Stellaris',
                    items: [
                        {
                            label: 'Research',
                            to: '/research',
                        },
                    ],
                },
                {
                    title: 'Community',
                    items: [
                        {
                            label: 'Discord',
                            href: 'https://discord.gg/7PyS4Ggd',
                        },
                    ],
                },
                {
                    title: 'More',
                    items: [
                        {
                            label: 'Blog',
                            to: '/blog',
                        },
                        {
                            label: 'GitHub',
                            href: 'https://github.com/danaketh/StellarisWiki',
                        },
                    ],
                },
            ],
            copyright: `Copyright © ${new Date().getFullYear()} Daniel Tlach. Built with Docusaurus.`,
        },
        prism: {
            theme: prismThemes.github,
            darkTheme: prismThemes.dracula,
        },
    } satisfies Preset.ThemeConfig,
};

export default config;
