import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
    research: [
        'research/index',
        {
            type: 'category',
            label: 'Engineering',
            link: {
                type: 'doc',
                id: 'research/engineering/index',
            },
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'research/engineering',
                },
            ],
        },
        {
            type: 'category',
            label: 'Physics',
            link: {
                type: 'doc',
                id: 'research/physics/index',
            },
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'research/physics',
                },
            ],
        },
        {
            type: 'category',
            label: 'Society',
            link: {
                type: 'doc',
                id: 'research/society/index',
            },
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'research/society',
                },
            ],
        },
    ],
};

export default sidebars;
